# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaoPortados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('operadora', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=64)),
                ('prefixo', models.BigIntegerField()),
                ('rn1', models.IntegerField()),
            ],
            options={
                'db_table': 'nao_portados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numero', models.BigIntegerField()),
                ('rn1', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('op', models.IntegerField()),
            ],
            options={
                'db_table': 'portados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefixo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ddd', models.IntegerField(null=True, blank=True)),
                ('prefixo', models.IntegerField(unique=True, null=True, blank=True)),
                ('inicial', models.IntegerField(null=True, blank=True)),
                ('final', models.IntegerField(null=True, blank=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('operadora', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('rn1', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'prefixo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SipBuddies',
            fields=[
                ('uniqueid', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=250)),
                ('accountcode', models.CharField(max_length=30, null=True, blank=True)),
                ('amaflags', models.CharField(max_length=1, null=True, blank=True)),
                ('callgroup', models.CharField(max_length=30, null=True, blank=True)),
                ('callerid', models.CharField(max_length=50, null=True, blank=True)),
                ('canreinvite', models.CharField(max_length=3, null=True, blank=True)),
                ('context', models.CharField(max_length=250, null=True, blank=True)),
                ('defaultip', models.CharField(max_length=15, null=True, blank=True)),
                ('dtmfmode', models.CharField(max_length=7, null=True, blank=True)),
                ('fromuser', models.CharField(max_length=50, null=True, blank=True)),
                ('fromdomain', models.CharField(max_length=31, null=True, blank=True)),
                ('host', models.CharField(max_length=31)),
                ('incominglimit', models.CharField(max_length=2, null=True, blank=True)),
                ('outgoinglimit', models.CharField(max_length=2, null=True, blank=True)),
                ('insecure', models.CharField(max_length=4, null=True, blank=True)),
                ('language', models.CharField(max_length=2, null=True, blank=True)),
                ('mailbox', models.CharField(max_length=50, null=True, blank=True)),
                ('md5secret', models.CharField(max_length=32, null=True, blank=True)),
                ('nat', models.CharField(max_length=5, null=True, blank=True)),
                ('permit', models.CharField(max_length=95, null=True, blank=True)),
                ('deny', models.CharField(max_length=95, null=True, blank=True)),
                ('pickupgroup', models.CharField(max_length=30, null=True, blank=True)),
                ('port', models.CharField(max_length=5)),
                ('qualify', models.CharField(max_length=4, null=True, blank=True)),
                ('restrictcid', models.CharField(max_length=3, null=True, blank=True)),
                ('rtptimeout', models.CharField(max_length=3, null=True, blank=True)),
                ('rtpholdtimeout', models.CharField(max_length=3, null=True, blank=True)),
                ('secret', models.CharField(max_length=30, null=True, blank=True)),
                ('type', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=30)),
                ('allow', models.CharField(max_length=100, null=True, blank=True)),
                ('disallow', models.CharField(max_length=100, null=True, blank=True)),
                ('regseconds', models.IntegerField()),
                ('ipaddr', models.CharField(max_length=15)),
                ('cliente', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'sip_buddies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numero', models.CharField(max_length=30)),
                ('hora', models.TimeField(auto_now=True)),
                ('cache', models.TimeField()),
                ('cliente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo', choices=[(b'Pessoa Fisica', b'Pessoa Fisica'), (b'Pessoa Juridica', b'Pessoa Juridica')])),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='SobreNome')),
                ('empresa', models.CharField(max_length=100, null=True, verbose_name='Nome fantasia', blank=True)),
                ('cpf', models.CharField(unique=True, max_length=20, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=20, unique=True, null=True, verbose_name='CNPJ', blank=True)),
                ('ie', models.CharField(max_length=20, null=True, verbose_name='Insc. Estadual', blank=True)),
                ('telefoneF', models.CharField(max_length=20, null=True, verbose_name='Telefone Fixo', blank=True)),
                ('telefoneM', models.CharField(max_length=20, null=True, verbose_name='Telefone Movel', blank=True)),
                ('email', models.EmailField(unique=True, max_length=254, verbose_name=b'Email')),
                ('email_contato', models.EmailField(max_length=254, null=True, verbose_name=b'Email contato', blank=True)),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome', blank=True)),
                ('endereco', models.CharField(max_length=100, null=True, verbose_name='Endere\xe7o', blank=True)),
                ('numero', models.CharField(max_length=100, null=True, verbose_name='N\xfamero', blank=True)),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro', blank=True)),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Complemento', blank=True)),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade', blank=True)),
                ('estado', models.CharField(max_length=100, null=True, verbose_name='Estado', blank=True)),
                ('cep', models.CharField(default=b'00000-000', max_length=10, verbose_name='CEP')),
                ('cod_cliente', models.IntegerField(unique=True, verbose_name='Codigo do Cliente')),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('plano', models.IntegerField(default=1, verbose_name='Plano')),
                ('cache', models.IntegerField(default=0, verbose_name='Cache')),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numero', models.CharField(max_length=30)),
                ('prefixo', models.IntegerField()),
                ('ddd', models.IntegerField()),
                ('rn1', models.IntegerField()),
                ('operadora', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('portado', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('cliente', models.ForeignKey(to='port.Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('plano', models.CharField(max_length=255, null=True, blank=True)),
                ('descricao', models.CharField(max_length=255, null=True, blank=True)),
                ('valor', models.DecimalField(default=0.0, null=True, max_digits=10, decimal_places=2, blank=True)),
                ('valor_consulta', models.FloatField(default=0.0, null=True, blank=True)),
                ('consultas_gratis', models.IntegerField(default=0, null=True, blank=True)),
                ('taxas', models.DecimalField(default=0.0, null=True, max_digits=10, decimal_places=2, blank=True)),
                ('tipo', models.CharField(default=1, max_length=200, choices=[(b'0', b'Ilimitado'), (b'1', b'normal')])),
            ],
        ),
        migrations.CreateModel(
            name='PlanoCliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cliente', models.IntegerField(default=1, unique=True, verbose_name='Cliente')),
                ('plano', models.IntegerField(default=1, verbose_name='Plano')),
                ('nome_plano', models.CharField(max_length=255, verbose_name='Nome do Plano')),
                ('consultas', models.IntegerField(default=0, null=True, blank=True)),
                ('consultas_gratis', models.IntegerField(default=0, null=True, blank=True)),
                ('criado_em', models.DateTimeField(default=datetime.datetime(2015, 7, 10, 17, 14, 14, 331609))),
                ('expira_em', models.DateTimeField(default=datetime.datetime(2015, 8, 9, 17, 14, 14, 331609))),
                ('tipo', models.CharField(default=1, max_length=200, choices=[(b'0', b'Ilimitado'), (b'1', b'normal')])),
                ('cache', models.CharField(default=0, max_length=1, verbose_name='Cache habilitado', choices=[(b'0', b'Desativado'), (b'1', b'Ativado')])),
                ('tempo', models.IntegerField(default=60, verbose_name='Tempo do cache em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateTimeField()),
                ('lastEventDate', models.DateTimeField()),
                ('code', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('status', models.CharField(default=1, max_length=200, choices=[(b'1', b'Aguardando pagamento'), (b'2', b'Em an\xc3\xa1lise'), (b'3', b'Pago'), (b'4', b'Dispon\xc3\xadvel'), (b'5', b'Em disputa'), (b'6', b'Devolvido'), (b'7', b'Cancelado'), (b'8', b'Valor devolvido'), (b'9', b'Em contesta\xc3\xa7\xc3\xa3o')])),
                ('paymentMethod', models.CharField(default=1, max_length=200, choices=[(b'1', b'Cart\xc3\xa3o de cr\xc3\xa9dito'), (b'2', b'Boleto'), (b'3', b'D\xc3\xa9bito online (TEF)'), (b'4', b'Saldo PagSeguro'), (b'5', b'Oi Paggo'), (b'7', b'Dep\xc3\xb3sito em conta')])),
                ('paymentMethodCode', models.CharField(default=101, max_length=200, choices=[(b'101', b'Cart\xc3\xa3o de cr\xc3\xa9dito Visa'), (b'102', b'Cart\xc3\xa3o de cr\xc3\xa9dito MasterCard'), (b'103', b'Cart\xc3\xa3o de cr\xc3\xa9dito American Express'), (b'104', b'Cart\xc3\xa3o de cr\xc3\xa9dito Diners'), (b'105', b'Cart\xc3\xa3o de cr\xc3\xa9dito Hipercard'), (b'106', b'Cart\xc3\xa3o de cr\xc3\xa9dito Aura'), (b'107', b'Cart\xc3\xa3o de cr\xc3\xa9dito Elo'), (b'108', b'Cart\xc3\xa3o de cr\xc3\xa9dito PLENOCard'), (b'109', b'Cart\xc3\xa3o de cr\xc3\xa9dito PersonalCard'), (b'110', b'Cart\xc3\xa3o de cr\xc3\xa9dito JCB'), (b'111', b'Cart\xc3\xa3o de cr\xc3\xa9dito Discover'), (b'112', b'Cart\xc3\xa3o de cr\xc3\xa9dito BrasilCard'), (b'113', b'Cart\xc3\xa3o de cr\xc3\xa9dito FORTBRASIL'), (b'114', b'Cart\xc3\xa3o de cr\xc3\xa9dito CARDBAN'), (b'115', b'Cart\xc3\xa3o de cr\xc3\xa9dito VALECARD'), (b'116', b'Cart\xc3\xa3o de cr\xc3\xa9dito Cabal'), (b'117', b'Cart\xc3\xa3o de cr\xc3\xa9dito Mais!'), (b'118', b'Cart\xc3\xa3o de cr\xc3\xa9dito Avista'), (b'119', b'Cart\xc3\xa3o de cr\xc3\xa9dito GRANDCARD'), (b'120', b'Cart\xc3\xa3o de cr\xc3\xa9dito Sorocred'), (b'201', b'Boleto Bradesco'), (b'202', b'Boleto Santander'), (b'301', b'D\xc3\xa9bito online Bradesco'), (b'302', b'D\xc3\xa9bito online Ita\xc3\xba'), (b'303', b'D\xc3\xa9bito online Unibanco'), (b'304', b'D\xc3\xa9bito online Banco do Brasil'), (b'305', b'D\xc3\xa9bito online Banco Real'), (b'306', b'D\xc3\xa9bito online Banrisul'), (b'307', b'D\xc3\xa9bito online HSBC'), (b'401', b'Saldo PagSeguro'), (b'501', b'Oi Paggo'), (b'701', b'Dep\xc3\xb3sito em conta - Banco do Brasil'), (b'702', b'Dep\xc3\xb3sito em conta - HSBC')])),
                ('grossAmount', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('discountAmount', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('netAmount', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('extraAmount', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('item', models.CharField(max_length=200)),
                ('id_plano', models.IntegerField()),
                ('controle', models.IntegerField(default=0)),
                ('consultas', models.IntegerField(default=0)),
                ('email', models.EmailField(default=b'email@email.com', max_length=254)),
                ('name', models.CharField(default=1, max_length=255)),
                ('phone', models.CharField(default=1, max_length=20)),
            ],
        ),
    ]
