CREATE TABLE `sip_buddies` (
  `uniqueid` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL DEFAULT '',
  `accountcode` varchar(30) DEFAULT NULL,
  `amaflags` char(1) DEFAULT NULL,
  `callgroup` varchar(30) DEFAULT NULL,
  `callerid` varchar(50) DEFAULT NULL,
  `canreinvite` char(3) DEFAULT NULL,
  `context` varchar(250) DEFAULT NULL,
  `defaultip` varchar(15) DEFAULT NULL,
  `dtmfmode` varchar(7) DEFAULT NULL,
  `fromuser` varchar(50) DEFAULT NULL,
  `fromdomain` varchar(31) DEFAULT NULL,
  `host` varchar(31) NOT NULL DEFAULT 'dynamic',
  `incominglimit` char(2) DEFAULT NULL,
  `outgoinglimit` char(2) DEFAULT NULL,
  `insecure` varchar(4) DEFAULT NULL,
  `language` char(2) DEFAULT NULL,
  `mailbox` varchar(50) DEFAULT NULL,
  `md5secret` varchar(32) DEFAULT NULL,
  `nat` varchar(5) DEFAULT NULL,
  `permit` varchar(95) DEFAULT NULL,
  `deny` varchar(95) DEFAULT NULL,
  `pickupgroup` varchar(30) DEFAULT NULL,
  `port` varchar(5) NOT NULL DEFAULT '',
  `qualify` varchar(4) DEFAULT 'yes',
  `useragent` varchar(255) DEFAULT NULL,
  `restrictcid` char(3) DEFAULT NULL,
  `lastms` int(11) DEFAULT NULL,
  `rtptimeout` char(3) DEFAULT NULL,
  `rtpholdtimeout` char(3) DEFAULT NULL,
  `fullcontact` varchar(255) DEFAULT NULL,
  `secret` varchar(30) DEFAULT NULL,
  `type` varchar(6) NOT NULL DEFAULT '',
  `username` varchar(30) NOT NULL DEFAULT '',
  `allow` varchar(100) DEFAULT NULL,
  `disallow` varchar(100) DEFAULT NULL,
  `regseconds` int(11) NOT NULL DEFAULT '0',
  `ipaddr` varchar(15) NOT NULL DEFAULT '',
  `cliente` int(11) DEFAULT NULL,
  PRIMARY KEY (`uniqueid`),
  UNIQUE KEY `name` (`name`),
  KEY `name_2` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;